# coding: utf-8

# flake8: noqa
"""
    Devo Model Manager API

    Devo API for machine learning  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: machine.learning@devo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from devo_model_manager_client.models.body import Body
from devo_model_manager_client.models.body1 import Body1
from devo_model_manager_client.models.cluster import Cluster
from devo_model_manager_client.models.field import Field
from devo_model_manager_client.models.image import Image
from devo_model_manager_client.models.login_response import LoginResponse
from devo_model_manager_client.models.model import Model
from devo_model_manager_client.models.model_detail import ModelDetail
from devo_model_manager_client.models.model_review import ModelReview
